const kdata_ = {
  type: "FeatureCollection",
  name: "building_store_demo",
  features: [
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/1",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2717167,
        longitude: 36.8139821,
      },
      geometry: { type: "Point", coordinates: [36.8139821, -1.2717167] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/2",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.271927,
        longitude: 36.814086,
      },
      geometry: { type: "Point", coordinates: [36.814086, -1.271927] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/3",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2637761,
        longitude: 36.8150454,
      },
      geometry: { type: "Point", coordinates: [36.8150454, -1.2637761] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/4",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2662179,
        longitude: 36.8028786,
      },
      geometry: { type: "Point", coordinates: [36.8028786, -1.2662179] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/5",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2666293,
        longitude: 36.8013785,
      },
      geometry: { type: "Point", coordinates: [36.8013785, -1.2666293] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/6",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2559963,
        longitude: 36.7933973,
      },
      geometry: { type: "Point", coordinates: [36.7933973, -1.2559963] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/7",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.256107,
        longitude: 36.7927704,
      },
      geometry: { type: "Point", coordinates: [36.7927704, -1.256107] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/8",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2558601,
        longitude: 36.7972066,
      },
      geometry: { type: "Point", coordinates: [36.7972066, -1.2558601] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/9",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2558497,
        longitude: 36.7965587,
      },
      geometry: { type: "Point", coordinates: [36.7965587, -1.2558497] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/10",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2560865,
        longitude: 36.7947348,
      },
      geometry: { type: "Point", coordinates: [36.7947348, -1.2560865] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/11",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2560712,
        longitude: 36.7926624,
      },
      geometry: { type: "Point", coordinates: [36.7926624, -1.2560712] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b1/12",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2662874,
        longitude: 36.8217669,
      },
      geometry: { type: "Point", coordinates: [36.8217669, -1.2662874] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/1",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2664878,
        longitude: 36.8210829,
      },
      geometry: { type: "Point", coordinates: [36.8210829, -1.2664878] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/2",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2651183,
        longitude: 36.8219583,
      },
      geometry: { type: "Point", coordinates: [36.8219583, -1.2651183] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/3",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.266634,
        longitude: 36.8210843,
      },
      geometry: { type: "Point", coordinates: [36.8210843, -1.266634] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/4",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2667111,
        longitude: 36.8211566,
      },
      geometry: { type: "Point", coordinates: [36.8211566, -1.2667111] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/5",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2667063,
        longitude: 36.8013715,
      },
      geometry: { type: "Point", coordinates: [36.8013715, -1.2667063] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/6",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2673932,
        longitude: 36.8012704,
      },
      geometry: { type: "Point", coordinates: [36.8012704, -1.2673932] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/7",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2668359,
        longitude: 36.7989622,
      },
      geometry: { type: "Point", coordinates: [36.7989622, -1.2668359] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/8",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2672103,
        longitude: 36.7996749,
      },
      geometry: { type: "Point", coordinates: [36.7996749, -1.2672103] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b2/9",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2676646,
        longitude: 36.7976891,
      },
      geometry: { type: "Point", coordinates: [36.7976891, -1.2676646] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/10",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2672669,
        longitude: 36.797713,
      },
      geometry: { type: "Point", coordinates: [36.797713, -1.2672669] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/11",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2636146,
        longitude: 36.8035781,
      },
      geometry: { type: "Point", coordinates: [36.8035781, -1.2636146] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/12",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2644256,
        longitude: 36.8043748,
      },
      geometry: { type: "Point", coordinates: [36.8043748, -1.2644256] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/13",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2692947,
        longitude: 36.8113001,
      },
      geometry: { type: "Point", coordinates: [36.8113001, -1.2692947] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/14",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2661462,
        longitude: 36.8116263,
      },
      geometry: { type: "Point", coordinates: [36.8116263, -1.2661462] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/15",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2664479,
        longitude: 36.8030988,
      },
      geometry: { type: "Point", coordinates: [36.8030988, -1.2664479] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/16",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2666997,
        longitude: 36.7992912,
      },
      geometry: { type: "Point", coordinates: [36.7992912, -1.2666997] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/17",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2673751,
        longitude: 36.7986887,
      },
      geometry: { type: "Point", coordinates: [36.7986887, -1.2673751] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/18",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2671805,
        longitude: 36.7974405,
      },
      geometry: { type: "Point", coordinates: [36.7974405, -1.2671805] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b2/19",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2697877,
        longitude: 36.8118591,
      },
      geometry: { type: "Point", coordinates: [36.8118591, -1.2697877] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b2/20",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.269037,
        longitude: 36.8115858,
      },
      geometry: { type: "Point", coordinates: [36.8115858, -1.269037] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b2/21",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2667502,
        longitude: 36.8118882,
      },
      geometry: { type: "Point", coordinates: [36.8118882, -1.2667502] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b2/22",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2644883,
        longitude: 36.8127016,
      },
      geometry: { type: "Point", coordinates: [36.8127016, -1.2644883] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/1",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2640591,
        longitude: 36.8128253,
      },
      geometry: { type: "Point", coordinates: [36.8128253, -1.2640591] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/2",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2635236,
        longitude: 36.8130487,
      },
      geometry: { type: "Point", coordinates: [36.8130487, -1.2635236] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/3",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.26267,
        longitude: 36.8138268,
      },
      geometry: { type: "Point", coordinates: [36.8138268, -1.26267] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/4",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2623263,
        longitude: 36.8136138,
      },
      geometry: { type: "Point", coordinates: [36.8136138, -1.2623263] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/5",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2641126,
        longitude: 36.8025161,
      },
      geometry: { type: "Point", coordinates: [36.8025161, -1.2641126] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/6",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2631619,
        longitude: 36.8034769,
      },
      geometry: { type: "Point", coordinates: [36.8034769, -1.2631619] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/7",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2645299,
        longitude: 36.8044561,
      },
      geometry: { type: "Point", coordinates: [36.8044561, -1.2645299] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/8",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2645903,
        longitude: 36.8046194,
      },
      geometry: { type: "Point", coordinates: [36.8046194, -1.2645903] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/9",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2638117,
        longitude: 36.8030744,
      },
      geometry: { type: "Point", coordinates: [36.8030744, -1.2638117] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/10",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2634617,
        longitude: 36.8034833,
      },
      geometry: { type: "Point", coordinates: [36.8034833, -1.2634617] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:c1/11",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2700361,
        longitude: 36.8017141,
      },
      geometry: { type: "Point", coordinates: [36.8017141, -1.2700361] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/12",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2708288,
        longitude: 36.8015521,
      },
      geometry: { type: "Point", coordinates: [36.8015521, -1.2708288] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/13",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2716108,
        longitude: 36.8018642,
      },
      geometry: { type: "Point", coordinates: [36.8018642, -1.2716108] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/14",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2667946,
        longitude: 36.801072,
      },
      geometry: { type: "Point", coordinates: [36.801072, -1.2667946] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/15",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2660961,
        longitude: 36.8004567,
      },
      geometry: { type: "Point", coordinates: [36.8004567, -1.2660961] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/16",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2630769,
        longitude: 36.805022,
      },
      geometry: { type: "Point", coordinates: [36.805022, -1.2630769] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/17",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2645152,
        longitude: 36.8050862,
      },
      geometry: { type: "Point", coordinates: [36.8050862, -1.2645152] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/18",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2635179,
        longitude: 36.8052041,
      },
      geometry: { type: "Point", coordinates: [36.8052041, -1.2635179] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/19",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2637082,
        longitude: 36.8055733,
      },
      geometry: { type: "Point", coordinates: [36.8055733, -1.2637082] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/20",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2636077,
        longitude: 36.807236,
      },
      geometry: { type: "Point", coordinates: [36.807236, -1.2636077] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/21",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.265773,
        longitude: 36.8153002,
      },
      geometry: { type: "Point", coordinates: [36.8153002, -1.265773] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/22",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.266242,
        longitude: 36.8161746,
      },
      geometry: { type: "Point", coordinates: [36.8161746, -1.266242] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/23",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2698541,
        longitude: 36.8016816,
      },
      geometry: { type: "Point", coordinates: [36.8016816, -1.2698541] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/24",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2665844,
        longitude: 36.7944357,
      },
      geometry: { type: "Point", coordinates: [36.7944357, -1.2665844] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/25",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2711082,
        longitude: 36.8011318,
      },
      geometry: { type: "Point", coordinates: [36.8011318, -1.2711082] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/26",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2654355,
        longitude: 36.8220443,
      },
      geometry: { type: "Point", coordinates: [36.8220443, -1.2654355] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/27",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2643182,
        longitude: 36.8224506,
      },
      geometry: { type: "Point", coordinates: [36.8224506, -1.2643182] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:c1/28",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2714097,
        longitude: 36.8018399,
      },
      geometry: { type: "Point", coordinates: [36.8018399, -1.2714097] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/1",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2665848,
        longitude: 36.80006,
      },
      geometry: { type: "Point", coordinates: [36.80006, -1.2665848] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/2",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2560568,
        longitude: 36.7922788,
      },
      geometry: { type: "Point", coordinates: [36.7922788, -1.2560568] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/3",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2563963,
        longitude: 36.791176,
      },
      geometry: { type: "Point", coordinates: [36.791176, -1.2563963] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/4",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2562982,
        longitude: 36.789903,
      },
      geometry: { type: "Point", coordinates: [36.789903, -1.2562982] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/5",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2558115,
        longitude: 36.7888865,
      },
      geometry: { type: "Point", coordinates: [36.7888865, -1.2558115] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/6",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2666227,
        longitude: 36.809722,
      },
      geometry: { type: "Point", coordinates: [36.809722, -1.2666227] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/7",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2677093,
        longitude: 36.8110068,
      },
      geometry: { type: "Point", coordinates: [36.8110068, -1.2677093] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/8",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2642119,
        longitude: 36.8238475,
      },
      geometry: { type: "Point", coordinates: [36.8238475, -1.2642119] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/9",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2641909,
        longitude: 36.8238107,
      },
      geometry: { type: "Point", coordinates: [36.8238107, -1.2641909] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/10",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2636238,
        longitude: 36.8230069,
      },
      geometry: { type: "Point", coordinates: [36.8230069, -1.2636238] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/11",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2636021,
        longitude: 36.8227396,
      },
      geometry: { type: "Point", coordinates: [36.8227396, -1.2636021] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/12",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2628722,
        longitude: 36.8210999,
      },
      geometry: { type: "Point", coordinates: [36.8210999, -1.2628722] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/13",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2562518,
        longitude: 36.7919419,
      },
      geometry: { type: "Point", coordinates: [36.7919419, -1.2562518] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d1/14",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2562194,
        longitude: 36.7915486,
      },
      geometry: { type: "Point", coordinates: [36.7915486, -1.2562194] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/15",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.256397,
        longitude: 36.7913241,
      },
      geometry: { type: "Point", coordinates: [36.7913241, -1.256397] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/16",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2565638,
        longitude: 36.7905501,
      },
      geometry: { type: "Point", coordinates: [36.7905501, -1.2565638] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/17",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2562454,
        longitude: 36.7896045,
      },
      geometry: { type: "Point", coordinates: [36.7896045, -1.2562454] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/18",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2559006,
        longitude: 36.7892191,
      },
      geometry: { type: "Point", coordinates: [36.7892191, -1.2559006] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/19",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2641002,
        longitude: 36.8041459,
      },
      geometry: { type: "Point", coordinates: [36.8041459, -1.2641002] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/20",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2637569,
        longitude: 36.8058328,
      },
      geometry: { type: "Point", coordinates: [36.8058328, -1.2637569] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/21",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2640457,
        longitude: 36.8042841,
      },
      geometry: { type: "Point", coordinates: [36.8042841, -1.2640457] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/22",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2656637,
        longitude: 36.8148886,
      },
      geometry: { type: "Point", coordinates: [36.8148886, -1.2656637] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/23",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2664896,
        longitude: 36.8171975,
      },
      geometry: { type: "Point", coordinates: [36.8171975, -1.2664896] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/24",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2649287,
        longitude: 36.8134023,
      },
      geometry: { type: "Point", coordinates: [36.8134023, -1.2649287] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/25",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2651599,
        longitude: 36.8137223,
      },
      geometry: { type: "Point", coordinates: [36.8137223, -1.2651599] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/26",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2672343,
        longitude: 36.8165332,
      },
      geometry: { type: "Point", coordinates: [36.8165332, -1.2672343] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/27",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2664389,
        longitude: 36.8170224,
      },
      geometry: { type: "Point", coordinates: [36.8170224, -1.2664389] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d1/28",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2657049,
        longitude: 36.817521,
      },
      geometry: { type: "Point", coordinates: [36.817521, -1.2657049] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/29",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2646842,
        longitude: 36.8050706,
      },
      geometry: { type: "Point", coordinates: [36.8050706, -1.2646842] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/30",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2662699,
        longitude: 36.8045783,
      },
      geometry: { type: "Point", coordinates: [36.8045783, -1.2662699] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/31",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2657452,
        longitude: 36.8204296,
      },
      geometry: { type: "Point", coordinates: [36.8204296, -1.2657452] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/32",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2649157,
        longitude: 36.819093,
      },
      geometry: { type: "Point", coordinates: [36.819093, -1.2649157] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/33",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2631067,
        longitude: 36.820045,
      },
      geometry: { type: "Point", coordinates: [36.820045, -1.2631067] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/34",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2630633,
        longitude: 36.820172,
      },
      geometry: { type: "Point", coordinates: [36.820172, -1.2630633] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/35",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.263698,
        longitude: 36.8170624,
      },
      geometry: { type: "Point", coordinates: [36.8170624, -1.263698] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/36",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.261156,
        longitude: 36.8048417,
      },
      geometry: { type: "Point", coordinates: [36.8048417, -1.261156] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/37",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.26015,
        longitude: 36.8020535,
      },
      geometry: { type: "Point", coordinates: [36.8020535, -1.26015] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/38",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2593357,
        longitude: 36.801896,
      },
      geometry: { type: "Point", coordinates: [36.801896, -1.2593357] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d1/39",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2626396,
        longitude: 36.7972342,
      },
      geometry: { type: "Point", coordinates: [36.7972342, -1.2626396] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/1",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2616716,
        longitude: 36.8043116,
      },
      geometry: { type: "Point", coordinates: [36.8043116, -1.2616716] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/2",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2609386,
        longitude: 36.8045564,
      },
      geometry: { type: "Point", coordinates: [36.8045564, -1.2609386] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/3",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2602845,
        longitude: 36.8046837,
      },
      geometry: { type: "Point", coordinates: [36.8046837, -1.2602845] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/4",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2606219,
        longitude: 36.8030361,
      },
      geometry: { type: "Point", coordinates: [36.8030361, -1.2606219] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/5",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2632238,
        longitude: 36.7991445,
      },
      geometry: { type: "Point", coordinates: [36.7991445, -1.2632238] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/6",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2647674,
        longitude: 36.7962191,
      },
      geometry: { type: "Point", coordinates: [36.7962191, -1.2647674] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/7",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2657103,
        longitude: 36.8205796,
      },
      geometry: { type: "Point", coordinates: [36.8205796, -1.2657103] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/8",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2653494,
        longitude: 36.8198663,
      },
      geometry: { type: "Point", coordinates: [36.8198663, -1.2653494] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/9",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2651433,
        longitude: 36.8195426,
      },
      geometry: { type: "Point", coordinates: [36.8195426, -1.2651433] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:d2/10",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2647807,
        longitude: 36.8194526,
      },
      geometry: { type: "Point", coordinates: [36.8194526, -1.2647807] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/11",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2640292,
        longitude: 36.8194762,
      },
      geometry: { type: "Point", coordinates: [36.8194762, -1.2640292] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/12",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2648379,
        longitude: 36.8205569,
      },
      geometry: { type: "Point", coordinates: [36.8205569, -1.2648379] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/13",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2557074,
        longitude: 36.7877954,
      },
      geometry: { type: "Point", coordinates: [36.7877954, -1.2557074] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/14",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2556968,
        longitude: 36.7872897,
      },
      geometry: { type: "Point", coordinates: [36.7872897, -1.2556968] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/15",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2549242,
        longitude: 36.7872122,
      },
      geometry: { type: "Point", coordinates: [36.7872122, -1.2549242] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/16",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.256682,
        longitude: 36.7869413,
      },
      geometry: { type: "Point", coordinates: [36.7869413, -1.256682] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/17",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2666725,
        longitude: 36.7999705,
      },
      geometry: { type: "Point", coordinates: [36.7999705, -1.2666725] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/18",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2667866,
        longitude: 36.8000979,
      },
      geometry: { type: "Point", coordinates: [36.8000979, -1.2667866] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/19",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2667776,
        longitude: 36.8054768,
      },
      geometry: { type: "Point", coordinates: [36.8054768, -1.2667776] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:d2/20",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2672171,
        longitude: 36.8051353,
      },
      geometry: { type: "Point", coordinates: [36.8051353, -1.2672171] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d2/21",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2665856,
        longitude: 36.8045874,
      },
      geometry: { type: "Point", coordinates: [36.8045874, -1.2665856] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d2/22",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2667765,
        longitude: 36.8054949,
      },
      geometry: { type: "Point", coordinates: [36.8054949, -1.2667765] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d2/23",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2667552,
        longitude: 36.8000767,
      },
      geometry: { type: "Point", coordinates: [36.8000767, -1.2667552] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:d2/24",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2669775,
        longitude: 36.8001363,
      },
      geometry: { type: "Point", coordinates: [36.8001363, -1.2669775] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/1",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2674914,
        longitude: 36.8001505,
      },
      geometry: { type: "Point", coordinates: [36.8001505, -1.2674914] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/2",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.266799,
        longitude: 36.8052636,
      },
      geometry: { type: "Point", coordinates: [36.8052636, -1.266799] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/3",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.26692,
        longitude: 36.805361,
      },
      geometry: { type: "Point", coordinates: [36.805361, -1.26692] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/4",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2668684,
        longitude: 36.8052462,
      },
      geometry: { type: "Point", coordinates: [36.8052462, -1.2668684] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/5",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2632303,
        longitude: 36.8216803,
      },
      geometry: { type: "Point", coordinates: [36.8216803, -1.2632303] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/6",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2622616,
        longitude: 36.8195883,
      },
      geometry: { type: "Point", coordinates: [36.8195883, -1.2622616] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/7",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.262127,
        longitude: 36.8195904,
      },
      geometry: { type: "Point", coordinates: [36.8195904, -1.262127] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/8",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2630692,
        longitude: 36.806024,
      },
      geometry: { type: "Point", coordinates: [36.806024, -1.2630692] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/9",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2628069,
        longitude: 36.8054095,
      },
      geometry: { type: "Point", coordinates: [36.8054095, -1.2628069] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/10",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2643296,
        longitude: 36.805326,
      },
      geometry: { type: "Point", coordinates: [36.805326, -1.2643296] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/11",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2654212,
        longitude: 36.804952,
      },
      geometry: { type: "Point", coordinates: [36.804952, -1.2654212] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/12",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2652077,
        longitude: 36.8058045,
      },
      geometry: { type: "Point", coordinates: [36.8058045, -1.2652077] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/13",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2667948,
        longitude: 36.8079241,
      },
      geometry: { type: "Point", coordinates: [36.8079241, -1.2667948] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/14",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.264963,
        longitude: 36.8081116,
      },
      geometry: { type: "Point", coordinates: [36.8081116, -1.264963] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/15",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2640013,
        longitude: 36.8074828,
      },
      geometry: { type: "Point", coordinates: [36.8074828, -1.2640013] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/16",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2555958,
        longitude: 36.787873,
      },
      geometry: { type: "Point", coordinates: [36.787873, -1.2555958] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:highridge",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/17",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2556136,
        longitude: 36.7874553,
      },
      geometry: { type: "Point", coordinates: [36.7874553, -1.2556136] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/18",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2561603,
        longitude: 36.786578,
      },
      geometry: { type: "Point", coordinates: [36.786578, -1.2561603] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/19",
        typeofstructure: "temporary structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2569441,
        longitude: 36.7877623,
      },
      geometry: { type: "Point", coordinates: [36.7877623, -1.2569441] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/20",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2652762,
        longitude: 36.8140237,
      },
      geometry: { type: "Point", coordinates: [36.8140237, -1.2652762] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/21",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2677133,
        longitude: 36.8165331,
      },
      geometry: { type: "Point", coordinates: [36.8165331, -1.2677133] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/22",
        typeofstructure: "permanent structure",
        description:
          "The building is located along ita road it  has 5 floors plus an extra floor for parking purposes",
        latitude: -1.2662994,
        longitude: 36.8176517,
      },
      geometry: { type: "Point", coordinates: [36.8176517, -1.2662994] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/23",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2642233,
        longitude: 36.8141652,
      },
      geometry: { type: "Point", coordinates: [36.8141652, -1.2642233] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/24",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2661467,
        longitude: 36.8081046,
      },
      geometry: { type: "Point", coordinates: [36.8081046, -1.2661467] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/25",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2670105,
        longitude: 36.8166887,
      },
      geometry: { type: "Point", coordinates: [36.8166887, -1.2670105] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/26",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2677809,
        longitude: 36.8173475,
      },
      geometry: { type: "Point", coordinates: [36.8173475, -1.2677809] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Kitusuru",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/27",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2675239,
        longitude: 36.8187781,
      },
      geometry: { type: "Point", coordinates: [36.8187781, -1.2675239] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/28",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2679322,
        longitude: 36.8197106,
      },
      geometry: { type: "Point", coordinates: [36.8197106, -1.2679322] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/29",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2573447,
        longitude: 36.7996673,
      },
      geometry: { type: "Point", coordinates: [36.7996673, -1.2573447] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/30",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2581168,
        longitude: 36.7994369,
      },
      geometry: { type: "Point", coordinates: [36.7994369, -1.2581168] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "Street name:Brookside Drive",
        builingnumber: "Building number:b3/31",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2579922,
        longitude: 36.7993228,
      },
      geometry: { type: "Point", coordinates: [36.7993228, -1.2579922] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/32",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2570501,
        longitude: 36.7997473,
      },
      geometry: { type: "Point", coordinates: [36.7997473, -1.2570501] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/33",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2560224,
        longitude: 36.7985217,
      },
      geometry: { type: "Point", coordinates: [36.7985217, -1.2560224] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/34",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2658919,
        longitude: 36.7991151,
      },
      geometry: { type: "Point", coordinates: [36.7991151, -1.2658919] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/35",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2653982,
        longitude: 36.7981854,
      },
      geometry: { type: "Point", coordinates: [36.7981854, -1.2653982] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/36",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2655365,
        longitude: 36.7974274,
      },
      geometry: { type: "Point", coordinates: [36.7974274, -1.2655365] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/37",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2656648,
        longitude: 36.7972404,
      },
      geometry: { type: "Point", coordinates: [36.7972404, -1.2656648] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/38",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2654721,
        longitude: 36.7967948,
      },
      geometry: { type: "Point", coordinates: [36.7967948, -1.2654721] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/39",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2654588,
        longitude: 36.7957163,
      },
      geometry: { type: "Point", coordinates: [36.7957163, -1.2654588] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/40",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2633355,
        longitude: 36.8192154,
      },
      geometry: { type: "Point", coordinates: [36.8192154, -1.2633355] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:parklands",
        streetname: "street name:Lentana road",
        builingnumber: "Building number:b3/41",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2632069,
        longitude: 36.8183364,
      },
      geometry: { type: "Point", coordinates: [36.8183364, -1.2632069] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/42",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2631713,
        longitude: 36.8181537,
      },
      geometry: { type: "Point", coordinates: [36.8181537, -1.2631713] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/43",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2629568,
        longitude: 36.8177986,
      },
      geometry: { type: "Point", coordinates: [36.8177986, -1.2629568] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/44",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.262812,
        longitude: 36.8178601,
      },
      geometry: { type: "Point", coordinates: [36.8178601, -1.262812] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/45",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2626339,
        longitude: 36.8175445,
      },
      geometry: { type: "Point", coordinates: [36.8175445, -1.2626339] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/46",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2635488,
        longitude: 36.8185816,
      },
      geometry: { type: "Point", coordinates: [36.8185816, -1.2635488] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/47",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.26316,
        longitude: 36.8182885,
      },
      geometry: { type: "Point", coordinates: [36.8182885, -1.26316] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/48",
        typeofstructure: "permanent structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2630295,
        longitude: 36.8180577,
      },
      geometry: { type: "Point", coordinates: [36.8180577, -1.2630295] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/49",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2629606,
        longitude: 36.8178943,
      },
      geometry: { type: "Point", coordinates: [36.8178943, -1.2629606] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/50",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2630128,
        longitude: 36.816537,
      },
      geometry: { type: "Point", coordinates: [36.816537, -1.2630128] },
    },
    {
      type: "Feature",
      properties: {
        subcounty: "sub-county: Westlands",
        ward: "Ward:Karura",
        streetname: "street name:1st Parklands Road",
        builingnumber: "Building number:b3/51",
        typeofstructure: "temporary structure",
        description: "Property,s gate is black with red middle fillers.\n",
        latitude: -1.2580473,
        longitude: 36.813615,
      },
      geometry: { type: "Point", coordinates: [36.813615, -1.2580473] },
    },
  ],
};

export default kdata_;
